import type { ScaleLadderPlan } from "@pax-backend/scenario-runner";

const smoothedSendJson = {
  sendJsonIntervalMs: 1_000,
  sendJsonFanoutMs: 1_000,
} as const;

export default {
  schemaVersion: 1,
  ladderId: "phase-5-v1-scale",
  description:
    "Phase 5 scale climb from 100 to 1000 concurrent games across 1 to 10 shard machines.",
  scenarioCatalogDir: "testing/scenarios",
  nemesisCatalogDir: "testing/nemeses",
  defaultScenarioId: "chat-steady-state",
  defaultMode: "load",
  defaultBackend: "live",
  defaultOracleScope: "scenario",
  rungs: [
    {
      rungId: "100g-1shard",
      concurrentGames: 100,
      shardMachines: 1,
      targetDurationMs: 1_800_000,
      rampMs: 120_000,
      sessionsPerGame: 1,
      ...smoothedSendJson,
      nemesisIds: ["no-faults", "shard-death-every-5m"],
      samplingProfile: "ramp",
      notes: "Phase 2-sized baseline, now emitted through the Phase 5 rung artifact path.",
    },
    {
      rungId: "250g-3shards",
      concurrentGames: 250,
      shardMachines: 3,
      targetDurationMs: 1_800_000,
      rampMs: 180_000,
      sessionsPerGame: 1,
      ...smoothedSendJson,
      nemesisIds: ["no-faults", "shard-death-every-5m"],
      samplingProfile: "ramp",
      notes: "First placement-distribution rung above the single-shard proof.",
    },
    {
      rungId: "500g-5shards",
      concurrentGames: 500,
      shardMachines: 5,
      targetDurationMs: 3_600_000,
      rampMs: 300_000,
      sessionsPerGame: 1,
      ...smoothedSendJson,
      nemesisIds: ["no-faults", "shard-death-every-5m", "api-kind-partition-burst"],
      samplingProfile: "ramp",
      notes: "Mid-ladder rung where API-partition nemesis joins the scale evidence.",
    },
    {
      rungId: "750g-8shards",
      concurrentGames: 750,
      shardMachines: 8,
      targetDurationMs: 3_600_000,
      rampMs: 420_000,
      sessionsPerGame: 1,
      ...smoothedSendJson,
      nemesisIds: ["no-faults", "shard-death-every-5m", "api-kind-partition-burst"],
      samplingProfile: "cliff_hold",
      notes: "Pre-target rung promoted to cliff_hold sampling to catch the first saturation signal.",
    },
    {
      rungId: "1000g-10shards",
      concurrentGames: 1000,
      shardMachines: 10,
      targetDurationMs: 86_400_000,
      rampMs: 600_000,
      sessionsPerGame: 1,
      ...smoothedSendJson,
      nemesisIds: ["no-faults", "shard-death-every-5m", "api-kind-partition-burst"],
      samplingProfile: "cliff_hold",
      notes: "Exit-soak target: 1000 concurrent games across 10 shard machines for 24 hours.",
    },
  ],
} satisfies ScaleLadderPlan;
